# SPDX-FileCopyrightText: 2025 Andrew Grimberg
# SPDX-License-Identifier: Apache-2.0

"""Stub file for _version module generated by hatch-vcs."""

__all__: list[str]

__version__: str
version: str
__version_tuple__: tuple[int | str, ...]
version_tuple: tuple[int | str, ...]
__commit_id__: str | None
commit_id: str | None
